### ISSUE TITLE
Support Android 11, 12 & 13

### ISSUE THREAD

**Issue by Haruma-VN** [nineteendo/pyvz2#58]
From Android 11, the permission to Android's folders has been limited by Google and you need to grant the permission through settings to allow the access. However, pyvz2 is not an application, just a script and has been blocked to access files on Android.

**Comment by Nineteendo** [comment]
Actually, the script needs to ask permission through the storage access framework (Issue https://github.com/Nineteendo/PVZ2tools/issues/12).
Though, there seem to be problems to modify normal files... Investigation is required.

**Comment by Dektra00** [comment]
Doesn't work on Android 13. Can you help me? Maybe there's something I missed, it said finished unpacking but nothing happened.
![Screenshot_2023-12-18-20-53-36-601_ru iiec pydroid3](https://github.com/nineteendo/pvz2tools/assets/154240216/fda829c4-4aea-4267-b93d-d32b56c003d3)
